<?php

/**
 * @file
 * Provides effects and operations for the Image API.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\image_effects\Component\ColorUtility;

/**
 * Implements hook_theme().
 */
function image_effects_theme() {
  return [
    // Render a color information box and string.
    'image_effects_color_detail' => [
      'variables' => [
        'color' => '#000000',
        'border' => FALSE,
        'border_color' => '#000000',
      ],
    ],
    // Background image effect - summary
    'image_effects_background_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Brightness image effect - summary
    'image_effects_brightness_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Color shift image effect - summary.
    'image_effects_color_shift_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Contrast image effect - summary
    'image_effects_contrast_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Set canvas image effect - summary
    'image_effects_set_canvas_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Set transparent color image effect - summary
    'image_effects_set_transparent_color_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Render a preview of the Text Overlay in the image effect UI.
    'image_effects_text_overlay_preview' => [
      'variables' => ['success' => FALSE, 'preview' => []],
    ],
    // Text overlay image effect - summary.
    'image_effects_text_overlay_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Watemark image effect - summary
    'image_effects_watermark_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Convolution image effect - summary
    'image_effects_convolution_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
    // Convolution sharpen image effect - summary
    'image_effects_convolution_sharpen_summary' => [
      'variables' => ['data' => NULL, 'effect' => []],
    ],
  ];
}

/**
 * Prepares variables to get a color info.
 *
 * Default template: image-effects-color-detail.html.twig.
 */
function image_effects_preprocess_image_effects_color_detail(&$variables) {
  $variables['#attached']['library'][] = 'image_effects/image_effects.admin.ui';
  if ($variables['color']) {
    if ($variables['border']) {
      if ($variables['border_color'] == 'matchLuma') {
        $variables['border_color'] = ColorUtility::matchLuma($variables['color']);
      }
      else {
        $variables['border_color'] = Unicode::substr($variables['border_color'], 0, 7);
      }
    }
    $variables['color_opacity'] = ColorUtility::rgbaToOpacity($variables['color']);
    $variables['color'] = Unicode::substr($variables['color'], 0, 7);
  }
}
